Feature: admin user to finish branch. Ref: #2

diff --git a/git-hooks/pre-flow-release-finish b/git-hooks/pre-flow-release-finish
--- a/git-hooks/pre-flow-release-finish
+++ b/git-hooks/pre-flow-release-finish
@@ -1,13 +1,23 @@
 #!/usr/bin/env bash
 set -e
 
+VERSION=$1
+
 SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-$SCRIPT_PATH/filter-flow-release-finish-message
-$SCRIPT_PATH/filter-flow-release-finish-tag-message
+. "$SCRIPT_PATH/modules/functions.sh"
 
-git add .
-git commit --amend --no-edit
+author_name=$(git config --list | grep user.name | tail -n 1 | cut -d "=" -f 2)
+if [[ "$ADMIN_USERS" =~ "$author_name" ]]; then
+  branch_name=hotfix/$VERSION
+  if [[ "${branch_name}" != "${CURRENT_BRANCH}" ]]; then
+    echo "fetch your ${branch_name} with: git fetch origin $branch_name:$branch_name"
+    exit 1
+  fi
+  git config pull.rebase true
+  git pull
+  exit 0
+fi
 
-echo "disable finish in local mode"
+echo "you can't finish in local mode"
 exit 1
